apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: portfolio-creator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/haverford-cc/portfolio-creator-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
