apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden-config-env
  namespace: bitwarden
data:
  DOMAIN: "https://bitwarden.dens.dev"
  SHOW_PASSWORD_HINT: "false"
  SIGNUPS_ALLOWED: "false"
  WEBSOCKET_ENABLED: "true"
