apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
  name: dens-dev
  namespace: cert-manager
spec:
  secretName: dens.dev-tls
  dnsNames:
    - dens.dev
    - "*.dens.dev"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
